######################## default configuration ####################
baseURL = "/"
title = "Remember who you are"
theme = "reporter"
# post pagination
paginate = "7"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "UA-180488591-2" # example : UA-123-45
# disqus short name
disqusShortname = "diving-deep" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language

# webp image quality
[imaging]
quality = 100


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"