# main menu

[[main]]
name = "Home"
url = "/"
weight = 1 

[[main]]
name = "About"
url = "about"
weight = 2

[[main]]
name = "Coaching"
url = "coaching"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4
