# main menu

[[main]]
name = "Home"
url = "/"
weight = 1 

[[main]]
name = "About"
url = "about"
weight = 2

[[main]]
name = "Podcast"
url = "coaching"
weight = 3

[[main]]
name = "Videos"
url = "https://www.youtube.com/channel/UCtzgR46uuVlL6Vc9AellN6g"
weight = 4
